# Generated by Django 5.1.1 on 2024-11-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autification', '0001_initial'),
        ('social', '0005_alter_comment_discusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribes',
            field=models.ManyToManyField(blank=True, to='social.community'),
        ),
    ]
