# Generated by Django 5.1.1 on 2024-12-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autification', '0003_remove_profile_subscribes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photos/'),
        ),
    ]
