# Generated by Django 5.1.1 on 2025-01-07 12:00

import autification.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autification', '0004_alter_profile_name_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[autification.models.file_validation], verbose_name='image'),
        ),
    ]
