# Generated by Django 5.1.1 on 2024-10-28 18:25

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post_html', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='genres',
            field=models.CharField(choices=[('games', 'Games'), ('films', 'Films'), ('programing', 'Programing'), ('sport', 'Sport'), ('fishing', 'Fishing')], max_length=40),
        ),
    ]
