# Generated by Django 5.1.1 on 2024-10-31 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_alter_community_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='social.community'),
        ),
    ]
