# Generated by Django 5.1.1 on 2024-10-31 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='discusion',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='social.community'),
        ),
    ]
