# Generated by Django 5.1.1 on 2024-11-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_discusion_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='discusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='social.discusion'),
        ),
    ]
