# Generated by Django 5.1.1 on 2024-11-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_comment_discusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.genre'),
        ),
    ]
