# Generated by Django 5.1.1 on 2025-01-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_genres_community_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discusion',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.community'),
        ),
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.community'),
        ),
    ]
